spring:
  profiles:
    active: test  #合并 application-test.yml 中的配置参数
  #上传文件设置
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
      #线程池配置信息
  thread:
    pool:
      corePoolSize: 10
      maxPoolSize: 20
      keepAliveSeconds: 120
      queueCapacity: 50

server:
  port: 8080


#mybatis配置信息
mybatis:
  configLocation: classpath:mybatis/MapperConfig.xml
  mapperLocations: classpath:mybatis/sql/*.xml,classpath:mybatis/sql/extend/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2.xml

mapper:
  identity: MYSQL

staticPath: D:/static/common
