spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    maxIdle: 200
    maxActive: 1024
    maxWait: 1000
  datasource:
    url: jdbc:mysql://119.23.242.234:9306/news?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username:  'root'
    password:  '123456'